# Trying out new typechecker 'ty' via 'uvx ty check' i.e. not installing
[environment]
python-version = "3.13"
[analysis]
respect-type-ignore-comments = false
[rules]
invalid-argument-type = "ignore"
invalid-assignment = "ignore"
missing-argument = "ignore"
unknown-argument = "ignore"
unresolved-attribute = "ignore"
unresolved-import = "ignore"
