# Trying out new typechecker 'ty' via 'uvx ty check' i.e. not installing
[analysis]
respect-type-ignore-comments = false
[rules]
call-non-callable = "ignore"
invalid-argument-type = "ignore"
invalid-assignment = "ignore"
missing-argument = "ignore"
possibly-missing-attribute = "ignore"
unknown-argument = "ignore"
unresolved-attribute = "ignore"
unresolved-import = "ignore"
