# Trying out new typechecker 'ty' via 'uvx ty check' i.e. not installing
[rules]
call-non-callable = "ignore"
invalid-argument-type = "ignore"
invalid-assignment = "ignore"
#invalid-key = "ignore"
#invalid-return-type = "ignore"
missing-argument = "ignore"
#no-matching-overload = "ignore"
#non-subscriptable = "ignore"
possibly-missing-attribute = "ignore"
unknown-argument = "ignore"
unresolved-attribute = "ignore"
unresolved-import = "ignore"
